{
  "CarryScene": null,
  "Name": null,
  "Description": null,
  "Width": 1,
  "Height": 1,
  "Placements": "Floor, Underground",
  "CanDrop": true,
  "DisablePickup": false,
  "IsStackable": false,
  "StackSize": 1,
  "ModelScene": null,
  "DropScene": null,
  "PlaceScene": null,
  "Icon": null,
  "DefaultTypeScene": null,
  "__references": [],
  "IsValid": true,
  "__version": 0
}